### ISSUE TITLE
Incorrect Signature message

### ISSUE THREAD

**Issue by tuzemec** [benmanns/tinypng#2]
I'm getting constant "IncorrectSignature: Does not appear to be a PNG file" message when I try to run it under Windows.
Any idea what can cause the problem?

**Comment by benmanns** [comment]
Hey @tuzemec, usually I run Linux, so I haven't tested this in Windows. Is the exception being raised from [line 19 in client.rb](https://github.com/benmanns/tinypng/blob/559079e3dcfeb10fd74e86de489a57026b0603b0/lib/tinypng/client.rb#L19)? That would mean that the TinyPNG servers are rejecting the image format.
